### ISSUE TITLE
Invisible radio buttons in xfce4

### ISSUE THREAD

**Issue by Koosewoos** [EliverLara/Ant-Dracula#16]
Hi there,
First of all, I love Ant Dracula and really appreciate your work. 

I would like to report an issue with radio buttons in xfce4 (currently on Debian 9.6 stable Xfce). I downloaded the theme this week, so I know it's not an issue that's been solved in a never version. 

As you can see in the screenshots I attached, the radio boxes in xfce4 menus (shown is the Window Manager menu) are invisible with the theme Ant Dracula. Switching to a lighter theme (Ant Bloody) they become visible again. 
![antbloodyscreenshot](https://user-images.githubusercontent.com/45319964/48973057-4c5f9480-f037-11e8-91e5-e32666eda506.png)
![antdraculascreenshot](https://user-images.githubusercontent.com/45319964/48973058-4cf82b00-f037-11e8-87bd-2a9dafa25eca.png)

I hope you can look into it, currently I'm just switching themes whenever I need to need to change some settings in Xfce4 (encountering the same issue in the Desktop menu, Keyboard menu etc).

**Comment by EliverLara** [comment]
Hi, I've just tested it in my xfce desktop (4.12), but everything seems to be ok:

![dracula](https://user-images.githubusercontent.com/9838260/48973665-1eb02680-f00a-11e8-8ef7-b3666897fbfc.png)

Are you sure it's not an installation issue?

**Comment by Koosewoos** [comment]
You're absolutely right, it was an installation issue. I just removed all the files and installed from github again, according to your instructions. That solved the issue. Thanks for the quick reaction!
It might be that I also had a Ant-Master file installed, I don't know. Anyway, the issue is now fixed, I have my radio boxes again :-)
