### ISSUE TITLE
[Remmina] [GNOME] [Ant-Dracula] dark icons on dark background in Remmina window

### ISSUE THREAD

**Issue by paullame** [EliverLara/Ant-Dracula#17]
![screenshot from 2018-11-26 11-01-49](https://user-images.githubusercontent.com/19651070/49007633-3acbd900-f16c-11e8-8ab1-af65172b326c.png)

In the Remmina application

The "Add" button left to "RDP" and the "clear text" icon in the text box are not easily visible and should be white.

I'm using the Paper icon set

best regards,
Paul

**Comment by EliverLara** [comment]
So far it seems to work right for me

![rommina](https://user-images.githubusercontent.com/9838260/49040986-9789bc80-f189-11e8-922b-59937079e946.png)

Could you provide more information about your OS, to try to reproduce it?

**Comment by paullame** [comment]
I don't know why the application layout is different in my case.
Here are my specs, Hope it will be able to help

![screenshot from 2018-11-27 10-42-48](https://user-images.githubusercontent.com/19651070/49073003-c9eef480-f231-11e8-9acf-ba72a2f45852.png)
![screenshot from 2018-11-27 10-45-17](https://user-images.githubusercontent.com/19651070/49073002-c9eef480-f231-11e8-818d-f52ec2f6df18.png)

thanks

**Comment by paullame** [comment]
Ok, nice find !
I guess I can close this then.
thanks :)
