### ISSUE TITLE
[problem]Application and Color Bar

### ISSUE THREAD

**Issue by TheLoser-2415** [EliverLara/Ant-Dracula#27]
Hello best regards.

**OS**: Ubuntu 18.04.3 LTS
**Theme Version**: Ant-Dracula-Slim with Mac buttons.

The problem I have is that the bar of the applications does not have the color black and also the bar stays large does not become slim. However the version of Ant-Dracula-alt-style the bar turns dark and the size is reduced a little, but, the colors of the options box (applications, cursors, icons) continue with the white color observed in the Photo.
![Desktop](https://user-images.githubusercontent.com/58609569/70355326-3f7ba080-1848-11ea-8c2f-eb216fc39b56.png)

Thank you very much and have a nice day!

**Comment by EliverLara** [comment]
It was a temporary issue while uploading tht theme.
