### ISSUE TITLE
Can't compile scss

### ISSUE THREAD

**Issue by bringmethecode** [EliverLara/Ant-Dracula#3]
Hello, first all lovely theme!

I am trying to modify some styles but I get lots of errors when I try to compile gtk.scss.

```
Error: expected selector.
  selection { @extend %selected_items:disabled; }
                                     ^
```

It seems that in sass you can't extend pseudo-classes, you must create a placeholder specific to each extend.

**Wrong:**
```
%foo {
   color: red;
   &:disabled {
      color: black;
   }
}

...

.bar {
   @extend %foo:disabled
}
```

**Right:**
```
%fooDisabled {
   color: black;
}

...

.bar:disabled {
   @extend %fooDisabled
}
```
Using @extend with nested classes is not recommended. It complicates things in bigger projects.

**Comment by EliverLara** [comment]
Hi, you're right, you get a lot of warnings, but that doesn't matter, you can still compile the file with your modifications, the warnings don't affect the compilation process.

**Comment by bringmethecode** [comment]
The problem is that those are not warnings, they are errors that stop the compiling process, so there is no .css output. I believe there were treated as warning is Ruby Sass, which is now deprecated. There is still an ongoing issue with @extend and Dart Sass (the new implementation of sass), here: https://github.com/sass/sass/issues/1599

So. anyone trying to compile the sources with Dart Sass will be unable to do it :(

**Comment by EliverLara** [comment]
You are right, but changing to dart-sass would imply an almost complete rewriting of the theme, personally I use gulp (with the plugin gulp-sass) for theme development, so perhaps that option may interest you.
