### ISSUE TITLE
budgie panel

### ISSUE THREAD

**Issue by denikris** [EliverLara/Ant-Dracula#30]
ubuntu-budgie 18.04.3
budgie-desktop 10.5

black square stroke in budgie panel when dynamic transparent active and maybe more polish for other budgie component

![Screenshot from 2020-01-15 09-26-26](https://user-images.githubusercontent.com/16707606/72399766-aeb6af80-3779-11ea-8cc8-0445b8b09dae.png)

**Comment by EliverLara** [comment]
Fixed!
