### ISSUE TITLE
ubuntu budgie raven sidebar size too big compared to budgie built in and replace power strip icon

### ISSUE THREAD

**Issue by denikris** [EliverLara/Ant-Dracula#35]
![Peek 2020-03-14 18-46](https://user-images.githubusercontent.com/16707606/76681354-aa492e80-6624-11ea-83cf-204deb1abd2a.gif)
ubuntu budgie 18.04.4
budgie-desktop 10.5 (from backport ppa)
raven sidebar too wide compared to budgie built-in theme, and maybe the blue purple red power strip in the bottom of raven can be replaced with the mono or symbolic

**Comment by EliverLara** [comment]
Thanks for reporting, I'll take a look.
