### ISSUE TITLE
render assets give inkscape warning error in Alt-style variant

### ISSUE THREAD

**Issue by denikris** [EliverLara/Ant-Dracula#36]
ubuntu budgie 18.04.x
budgie desktop 10.5.x

first i deleted all png files except the symlink file in **gtk-2.0/assets/**, then i run `./render-assets.sh` in user level in home directory and get this error
```
Rendering assets/menu-checkbox.png

** (inkscape:25146): WARNING **: 18:41:48.326: Invalid option --export-file=assets/menu-checkbox.png

Rendering assets/menu-checkbox-hover.png

** (inkscape:25198): WARNING **: 18:41:48.424: Invalid option --export-file=assets/menu-checkbox-hover.png
```
and no png images produced in **assets** folder

**Comment by EliverLara** [comment]
Hi, I have updated my system and inkscape has been updated to its latest version so the script had to be adapted, you can find the previous version [on this commit](https://github.com/EliverLara/Ant-Dracula/commit/fc22d61a734f0348cc8c3f98f9947e0da629edc7#diff-d15df9f9278de450366164fb517ea027).
