### ISSUE TITLE
Default gnome blue in top bar menu

### ISSUE THREAD

**Issue by rustysec** [EliverLara/Ant-Dracula#37]
![image](https://user-images.githubusercontent.com/6980201/77188995-1ba93700-6a94-11ea-9a2e-6b0248e0425b.png)

I looked through the css but couldn't pin down where this was coming from. Happens using both dash to dock and the regular panel

**Comment by EliverLara** [comment]
Fixed!

**Comment by MarcosIgnacioo** [comment]
how do you fix this :cry:
