### ISSUE TITLE
can't change it

### ISSUE THREAD

**Issue by lovezyou** [EliverLara/Ant-Dracula#38]
i install it in terminal . but now i want to change it but it not change.

**Comment by EliverLara** [comment]
Hi, Are you using gnome? if so, try changing themes with [gnome tweaks](https://itsfoss.com/gnome-tweak-tool/)

**Comment by lovezyou** [comment]
I'm using kali linux 2020.1 . and it has KDE system seting. but it won't work.

**Comment by EliverLara** [comment]
Does this still persist?

**Comment by lovezyou** [comment]
yes....

**Comment by EliverLara** [comment]
Sometimes kde has problems with cached themes, so you could manually set the theme for each section (aurorae, plasma, color scheme)
