### ISSUE TITLE
Theme has not been 'released' in a long time

### ISSUE THREAD

**Issue by mmartinez** [EliverLara/Ant-Dracula#42]
First of all, thanks for making this great theme. 

I'd like to request a new release since the last one (v1.3.0) was done in Jan 2019. Since then many fixes have been applied to the master branch, but have not been tagged as a release. Many package managers use github releases as a reference for the latest version of the theme, and don't use the master branch. Thus, delaying updates for the users.

 Thanks!

**Comment by Vonfry** [comment]
I have the same question. I want to packet this theme but the last tag looks old.
