### ISSUE TITLE
elementary os problem 

### ISSUE THREAD

**Issue by Belmaj** [EliverLara/Ant-Dracula#47]
i want to add this issue 
![Screenshot from 2020-05-08 21-07-43](https://user-images.githubusercontent.com/57773946/81413651-5d8f5900-9178-11ea-982f-b039258e1bfd.png)
can you pls sir fix this and make the text color pink.. thank you sir and also can you pls make the
background color for all applications 1e1f29 if its okay to you sir
i love this theme sir thanks for making this theme in gtk3 ..

**Comment by EliverLara** [comment]
Fixed!
