### ISSUE TITLE
Traffic light colors are disordered

### ISSUE THREAD

**Issue by Sshahar** [EliverLara/Ant-Dracula#9]
On Ubuntu 18.04, the colors from left to right are: Yellow Green Red.
![screenshot from 2018-08-04 02-49-19](https://user-images.githubusercontent.com/16301090/43670097-0c231058-9791-11e8-8553-80efea0c064e.png)

**Comment by EliverLara** [comment]
Hi, this is not an issue related to the theme, that depends on your button-layout configuration, you can change it using the dconf editor.
